theme: jekyll-theme-slate
title: Teaching Machines to Code
description: Neural Markup Generation with Visual Attention
show_downloads: false
defaults:
  -
    scope:
      path: ""
    values:
      title: Teaching Machines to Code
      description: Neural Markup Generation with Visual Attention
github:
  owner_name: Sumeet Singh
